#ifndef GEAROEMIX_RENDER_SHADER_SHADER_HPP
#define GEAROEMIX_RENDER_SHADER_SHADER_HPP
#include "../../core/asset/cr-asset.hpp"
#include "../../core/cr-types.hpp"
#include <memory>
#include <vector>
namespace gearoenix {
namespace core {
    class EndCaller;
}
namespace system {
    class File;
}
namespace render {
    class Engine;
    namespace shader {
        enum Id : core::Id {
            DIRECTIONAL_COLORED_MATTE_BAKED_CASTER_CUTOFF = 2112,
            DIRECTIONAL_COLORED_MATTE_BAKED_CASTER_OPAQUE = 960,
            DIRECTIONAL_COLORED_MATTE_BAKED_CASTER_TRANSPARENT = 1536,
            DIRECTIONAL_COLORED_MATTE_BAKED_FULL_CUTOFF = 2256,
            DIRECTIONAL_COLORED_MATTE_BAKED_FULL_OPAQUE = 1104,
            DIRECTIONAL_COLORED_MATTE_BAKED_FULL_TRANSPARENT = 1680,
            DIRECTIONAL_COLORED_MATTE_BAKED_SHADOWLESS_CUTOFF = 1968,
            DIRECTIONAL_COLORED_MATTE_BAKED_SHADOWLESS_OPAQUE = 816,
            DIRECTIONAL_COLORED_MATTE_BAKED_SHADOWLESS_TRANSPARENT = 1392,
            DIRECTIONAL_COLORED_MATTE_NONREFLECTIVE_CASTER_CUTOFF = 2076,
            DIRECTIONAL_COLORED_MATTE_NONREFLECTIVE_CASTER_OPAQUE = 924,
            DIRECTIONAL_COLORED_MATTE_NONREFLECTIVE_CASTER_TRANSPARENT = 1500,
            DIRECTIONAL_COLORED_MATTE_NONREFLECTIVE_FULL_CUTOFF = 2220,
            DIRECTIONAL_COLORED_MATTE_NONREFLECTIVE_FULL_OPAQUE = 1068,
            DIRECTIONAL_COLORED_MATTE_NONREFLECTIVE_FULL_TRANSPARENT = 1644,
            DIRECTIONAL_COLORED_MATTE_NONREFLECTIVE_SHADOWLESS_CUTOFF = 1932,
            DIRECTIONAL_COLORED_MATTE_NONREFLECTIVE_SHADOWLESS_OPAQUE = 780,
            DIRECTIONAL_COLORED_MATTE_NONREFLECTIVE_SHADOWLESS_TRANSPARENT = 1356,
            DIRECTIONAL_COLORED_MATTE_REALTIME_CASTER_CUTOFF = 2148,
            DIRECTIONAL_COLORED_MATTE_REALTIME_CASTER_OPAQUE = 996,
            DIRECTIONAL_COLORED_MATTE_REALTIME_CASTER_TRANSPARENT = 1572,
            DIRECTIONAL_COLORED_MATTE_REALTIME_FULL_CUTOFF = 2292,
            DIRECTIONAL_COLORED_MATTE_REALTIME_FULL_OPAQUE = 1140,
            DIRECTIONAL_COLORED_MATTE_REALTIME_FULL_TRANSPARENT = 1716,
            DIRECTIONAL_COLORED_MATTE_REALTIME_SHADOWLESS_CUTOFF = 2004,
            DIRECTIONAL_COLORED_MATTE_REALTIME_SHADOWLESS_OPAQUE = 852,
            DIRECTIONAL_COLORED_MATTE_REALTIME_SHADOWLESS_TRANSPARENT = 1428,
            DIRECTIONAL_COLORED_SPECULATED_BAKED_CASTER_CUTOFF = 2124,
            DIRECTIONAL_COLORED_SPECULATED_BAKED_CASTER_OPAQUE = 972,
            DIRECTIONAL_COLORED_SPECULATED_BAKED_CASTER_TRANSPARENT = 1548,
            DIRECTIONAL_COLORED_SPECULATED_BAKED_FULL_CUTOFF = 2268,
            DIRECTIONAL_COLORED_SPECULATED_BAKED_FULL_OPAQUE = 1116,
            DIRECTIONAL_COLORED_SPECULATED_BAKED_FULL_TRANSPARENT = 1692,
            DIRECTIONAL_COLORED_SPECULATED_BAKED_SHADOWLESS_CUTOFF = 1980,
            DIRECTIONAL_COLORED_SPECULATED_BAKED_SHADOWLESS_OPAQUE = 828,
            DIRECTIONAL_COLORED_SPECULATED_BAKED_SHADOWLESS_TRANSPARENT = 1404,
            DIRECTIONAL_COLORED_SPECULATED_NONREFLECTIVE_CASTER_CUTOFF = 2088,
            DIRECTIONAL_COLORED_SPECULATED_NONREFLECTIVE_CASTER_OPAQUE = 936,
            DIRECTIONAL_COLORED_SPECULATED_NONREFLECTIVE_CASTER_TRANSPARENT = 1512,
            DIRECTIONAL_COLORED_SPECULATED_NONREFLECTIVE_FULL_CUTOFF = 2232,
            DIRECTIONAL_COLORED_SPECULATED_NONREFLECTIVE_FULL_OPAQUE = 1080,
            DIRECTIONAL_COLORED_SPECULATED_NONREFLECTIVE_FULL_TRANSPARENT = 1656,
            DIRECTIONAL_COLORED_SPECULATED_NONREFLECTIVE_SHADOWLESS_CUTOFF = 1944,
            DIRECTIONAL_COLORED_SPECULATED_NONREFLECTIVE_SHADOWLESS_OPAQUE = 792,
            DIRECTIONAL_COLORED_SPECULATED_NONREFLECTIVE_SHADOWLESS_TRANSPARENT = 1368,
            DIRECTIONAL_COLORED_SPECULATED_REALTIME_CASTER_CUTOFF = 2160,
            DIRECTIONAL_COLORED_SPECULATED_REALTIME_CASTER_OPAQUE = 1008,
            DIRECTIONAL_COLORED_SPECULATED_REALTIME_CASTER_TRANSPARENT = 1584,
            DIRECTIONAL_COLORED_SPECULATED_REALTIME_FULL_CUTOFF = 2304,
            DIRECTIONAL_COLORED_SPECULATED_REALTIME_FULL_OPAQUE = 1152,
            DIRECTIONAL_COLORED_SPECULATED_REALTIME_FULL_TRANSPARENT = 1728,
            DIRECTIONAL_COLORED_SPECULATED_REALTIME_SHADOWLESS_CUTOFF = 2016,
            DIRECTIONAL_COLORED_SPECULATED_REALTIME_SHADOWLESS_OPAQUE = 864,
            DIRECTIONAL_COLORED_SPECULATED_REALTIME_SHADOWLESS_TRANSPARENT = 1440,
            DIRECTIONAL_TEXTURED_MATTE_BAKED_CASTER_CUTOFF = 2116,
            DIRECTIONAL_TEXTURED_MATTE_BAKED_CASTER_OPAQUE = 964,
            DIRECTIONAL_TEXTURED_MATTE_BAKED_CASTER_TRANSPARENT = 1540,
            DIRECTIONAL_TEXTURED_MATTE_BAKED_FULL_CUTOFF = 2260,
            DIRECTIONAL_TEXTURED_MATTE_BAKED_FULL_OPAQUE = 1108,
            DIRECTIONAL_TEXTURED_MATTE_BAKED_FULL_TRANSPARENT = 1684,
            DIRECTIONAL_TEXTURED_MATTE_BAKED_SHADOWLESS_CUTOFF = 1972,
            DIRECTIONAL_TEXTURED_MATTE_BAKED_SHADOWLESS_OPAQUE = 820,
            DIRECTIONAL_TEXTURED_MATTE_BAKED_SHADOWLESS_TRANSPARENT = 1396,
            DIRECTIONAL_TEXTURED_MATTE_NONREFLECTIVE_CASTER_CUTOFF = 2080,
            DIRECTIONAL_TEXTURED_MATTE_NONREFLECTIVE_CASTER_OPAQUE = 928,
            DIRECTIONAL_TEXTURED_MATTE_NONREFLECTIVE_CASTER_TRANSPARENT = 1504,
            DIRECTIONAL_TEXTURED_MATTE_NONREFLECTIVE_FULL_CUTOFF = 2224,
            DIRECTIONAL_TEXTURED_MATTE_NONREFLECTIVE_FULL_OPAQUE = 1072,
            DIRECTIONAL_TEXTURED_MATTE_NONREFLECTIVE_FULL_TRANSPARENT = 1648,
            DIRECTIONAL_TEXTURED_MATTE_NONREFLECTIVE_SHADOWLESS_CUTOFF = 1936,
            DIRECTIONAL_TEXTURED_MATTE_NONREFLECTIVE_SHADOWLESS_OPAQUE = 784,
            DIRECTIONAL_TEXTURED_MATTE_NONREFLECTIVE_SHADOWLESS_TRANSPARENT = 1360,
            DIRECTIONAL_TEXTURED_MATTE_REALTIME_CASTER_CUTOFF = 2152,
            DIRECTIONAL_TEXTURED_MATTE_REALTIME_CASTER_OPAQUE = 1000,
            DIRECTIONAL_TEXTURED_MATTE_REALTIME_CASTER_TRANSPARENT = 1576,
            DIRECTIONAL_TEXTURED_MATTE_REALTIME_FULL_CUTOFF = 2296,
            DIRECTIONAL_TEXTURED_MATTE_REALTIME_FULL_OPAQUE = 1144,
            DIRECTIONAL_TEXTURED_MATTE_REALTIME_FULL_TRANSPARENT = 1720,
            DIRECTIONAL_TEXTURED_MATTE_REALTIME_SHADOWLESS_CUTOFF = 2008,
            DIRECTIONAL_TEXTURED_MATTE_REALTIME_SHADOWLESS_OPAQUE = 856,
            DIRECTIONAL_TEXTURED_MATTE_REALTIME_SHADOWLESS_TRANSPARENT = 1432,
            DIRECTIONAL_TEXTURED_SPECULATED_BAKED_CASTER_CUTOFF = 2128,
            DIRECTIONAL_TEXTURED_SPECULATED_BAKED_CASTER_OPAQUE = 976,
            DIRECTIONAL_TEXTURED_SPECULATED_BAKED_CASTER_TRANSPARENT = 1552,
            DIRECTIONAL_TEXTURED_SPECULATED_BAKED_FULL_CUTOFF = 2272,
            DIRECTIONAL_TEXTURED_SPECULATED_BAKED_FULL_OPAQUE = 1120,
            DIRECTIONAL_TEXTURED_SPECULATED_BAKED_FULL_TRANSPARENT = 1696,
            DIRECTIONAL_TEXTURED_SPECULATED_BAKED_SHADOWLESS_CUTOFF = 1984,
            DIRECTIONAL_TEXTURED_SPECULATED_BAKED_SHADOWLESS_OPAQUE = 832,
            DIRECTIONAL_TEXTURED_SPECULATED_BAKED_SHADOWLESS_TRANSPARENT = 1408,
            DIRECTIONAL_TEXTURED_SPECULATED_NONREFLECTIVE_CASTER_CUTOFF = 2092,
            DIRECTIONAL_TEXTURED_SPECULATED_NONREFLECTIVE_CASTER_OPAQUE = 940,
            DIRECTIONAL_TEXTURED_SPECULATED_NONREFLECTIVE_CASTER_TRANSPARENT = 1516,
            DIRECTIONAL_TEXTURED_SPECULATED_NONREFLECTIVE_FULL_CUTOFF = 2236,
            DIRECTIONAL_TEXTURED_SPECULATED_NONREFLECTIVE_FULL_OPAQUE = 1084,
            DIRECTIONAL_TEXTURED_SPECULATED_NONREFLECTIVE_FULL_TRANSPARENT = 1660,
            DIRECTIONAL_TEXTURED_SPECULATED_NONREFLECTIVE_SHADOWLESS_CUTOFF = 1948,
            DIRECTIONAL_TEXTURED_SPECULATED_NONREFLECTIVE_SHADOWLESS_OPAQUE = 796,
            DIRECTIONAL_TEXTURED_SPECULATED_NONREFLECTIVE_SHADOWLESS_TRANSPARENT = 1372,
            DIRECTIONAL_TEXTURED_SPECULATED_REALTIME_CASTER_CUTOFF = 2164,
            DIRECTIONAL_TEXTURED_SPECULATED_REALTIME_CASTER_OPAQUE = 1012,
            DIRECTIONAL_TEXTURED_SPECULATED_REALTIME_CASTER_TRANSPARENT = 1588,
            DIRECTIONAL_TEXTURED_SPECULATED_REALTIME_FULL_CUTOFF = 2308,
            DIRECTIONAL_TEXTURED_SPECULATED_REALTIME_FULL_OPAQUE = 1156,
            DIRECTIONAL_TEXTURED_SPECULATED_REALTIME_FULL_TRANSPARENT = 1732,
            DIRECTIONAL_TEXTURED_SPECULATED_REALTIME_SHADOWLESS_CUTOFF = 2020,
            DIRECTIONAL_TEXTURED_SPECULATED_REALTIME_SHADOWLESS_OPAQUE = 868,
            DIRECTIONAL_TEXTURED_SPECULATED_REALTIME_SHADOWLESS_TRANSPARENT = 1444,
            SHADELESS_COLORED_MATTE_BAKED_CASTER_CUTOFF = 2111,
            SHADELESS_COLORED_MATTE_BAKED_CASTER_OPAQUE = 959,
            SHADELESS_COLORED_MATTE_BAKED_CASTER_TRANSPARENT = 1535,
            SHADELESS_COLORED_MATTE_BAKED_FULL_CUTOFF = 2255,
            SHADELESS_COLORED_MATTE_BAKED_FULL_OPAQUE = 1103,
            SHADELESS_COLORED_MATTE_BAKED_FULL_TRANSPARENT = 1679,
            SHADELESS_COLORED_MATTE_BAKED_SHADOWLESS_CUTOFF = 1967,
            SHADELESS_COLORED_MATTE_BAKED_SHADOWLESS_OPAQUE = 815,
            SHADELESS_COLORED_MATTE_BAKED_SHADOWLESS_TRANSPARENT = 1391,
            SHADELESS_COLORED_MATTE_NONREFLECTIVE_CASTER_CUTOFF = 2075,
            SHADELESS_COLORED_MATTE_NONREFLECTIVE_CASTER_OPAQUE = 923,
            SHADELESS_COLORED_MATTE_NONREFLECTIVE_CASTER_TRANSPARENT = 1499,
            SHADELESS_COLORED_MATTE_NONREFLECTIVE_FULL_CUTOFF = 2219,
            SHADELESS_COLORED_MATTE_NONREFLECTIVE_FULL_OPAQUE = 1067,
            SHADELESS_COLORED_MATTE_NONREFLECTIVE_FULL_TRANSPARENT = 1643,
            SHADELESS_COLORED_MATTE_NONREFLECTIVE_SHADOWLESS_CUTOFF = 1931,
            SHADELESS_COLORED_MATTE_NONREFLECTIVE_SHADOWLESS_OPAQUE = 779,
            SHADELESS_COLORED_MATTE_NONREFLECTIVE_SHADOWLESS_TRANSPARENT = 1355,
            SHADELESS_COLORED_MATTE_REALTIME_CASTER_CUTOFF = 2147,
            SHADELESS_COLORED_MATTE_REALTIME_CASTER_OPAQUE = 995,
            SHADELESS_COLORED_MATTE_REALTIME_CASTER_TRANSPARENT = 1571,
            SHADELESS_COLORED_MATTE_REALTIME_FULL_CUTOFF = 2291,
            SHADELESS_COLORED_MATTE_REALTIME_FULL_OPAQUE = 1139,
            SHADELESS_COLORED_MATTE_REALTIME_FULL_TRANSPARENT = 1715,
            SHADELESS_COLORED_MATTE_REALTIME_SHADOWLESS_CUTOFF = 2003,
            SHADELESS_COLORED_MATTE_REALTIME_SHADOWLESS_OPAQUE = 851,
            SHADELESS_COLORED_MATTE_REALTIME_SHADOWLESS_TRANSPARENT = 1427,
            SHADELESS_COLORED_SPECULATED_BAKED_CASTER_CUTOFF = 2123,
            SHADELESS_COLORED_SPECULATED_BAKED_CASTER_OPAQUE = 971,
            SHADELESS_COLORED_SPECULATED_BAKED_CASTER_TRANSPARENT = 1547,
            SHADELESS_COLORED_SPECULATED_BAKED_FULL_CUTOFF = 2267,
            SHADELESS_COLORED_SPECULATED_BAKED_FULL_OPAQUE = 1115,
            SHADELESS_COLORED_SPECULATED_BAKED_FULL_TRANSPARENT = 1691,
            SHADELESS_COLORED_SPECULATED_BAKED_SHADOWLESS_CUTOFF = 1979,
            SHADELESS_COLORED_SPECULATED_BAKED_SHADOWLESS_OPAQUE = 827,
            SHADELESS_COLORED_SPECULATED_BAKED_SHADOWLESS_TRANSPARENT = 1403,
            SHADELESS_COLORED_SPECULATED_NONREFLECTIVE_CASTER_CUTOFF = 2087,
            SHADELESS_COLORED_SPECULATED_NONREFLECTIVE_CASTER_OPAQUE = 935,
            SHADELESS_COLORED_SPECULATED_NONREFLECTIVE_CASTER_TRANSPARENT = 1511,
            SHADELESS_COLORED_SPECULATED_NONREFLECTIVE_FULL_CUTOFF = 2231,
            SHADELESS_COLORED_SPECULATED_NONREFLECTIVE_FULL_OPAQUE = 1079,
            SHADELESS_COLORED_SPECULATED_NONREFLECTIVE_FULL_TRANSPARENT = 1655,
            SHADELESS_COLORED_SPECULATED_NONREFLECTIVE_SHADOWLESS_CUTOFF = 1943,
            SHADELESS_COLORED_SPECULATED_NONREFLECTIVE_SHADOWLESS_OPAQUE = 791,
            SHADELESS_COLORED_SPECULATED_NONREFLECTIVE_SHADOWLESS_TRANSPARENT = 1367,
            SHADELESS_COLORED_SPECULATED_REALTIME_CASTER_CUTOFF = 2159,
            SHADELESS_COLORED_SPECULATED_REALTIME_CASTER_OPAQUE = 1007,
            SHADELESS_COLORED_SPECULATED_REALTIME_CASTER_TRANSPARENT = 1583,
            SHADELESS_COLORED_SPECULATED_REALTIME_FULL_CUTOFF = 2303,
            SHADELESS_COLORED_SPECULATED_REALTIME_FULL_OPAQUE = 1151,
            SHADELESS_COLORED_SPECULATED_REALTIME_FULL_TRANSPARENT = 1727,
            SHADELESS_COLORED_SPECULATED_REALTIME_SHADOWLESS_CUTOFF = 2015,
            SHADELESS_COLORED_SPECULATED_REALTIME_SHADOWLESS_OPAQUE = 863,
            SHADELESS_COLORED_SPECULATED_REALTIME_SHADOWLESS_TRANSPARENT = 1439,
            SHADELESS_TEXTURED_MATTE_BAKED_CASTER_CUTOFF = 2115,
            SHADELESS_TEXTURED_MATTE_BAKED_CASTER_OPAQUE = 963,
            SHADELESS_TEXTURED_MATTE_BAKED_CASTER_TRANSPARENT = 1539,
            SHADELESS_TEXTURED_MATTE_BAKED_FULL_CUTOFF = 2259,
            SHADELESS_TEXTURED_MATTE_BAKED_FULL_OPAQUE = 1107,
            SHADELESS_TEXTURED_MATTE_BAKED_FULL_TRANSPARENT = 1683,
            SHADELESS_TEXTURED_MATTE_BAKED_SHADOWLESS_CUTOFF = 1971,
            SHADELESS_TEXTURED_MATTE_BAKED_SHADOWLESS_OPAQUE = 819,
            SHADELESS_TEXTURED_MATTE_BAKED_SHADOWLESS_TRANSPARENT = 1395,
            SHADELESS_TEXTURED_MATTE_NONREFLECTIVE_CASTER_CUTOFF = 2079,
            SHADELESS_TEXTURED_MATTE_NONREFLECTIVE_CASTER_OPAQUE = 927,
            SHADELESS_TEXTURED_MATTE_NONREFLECTIVE_CASTER_TRANSPARENT = 1503,
            SHADELESS_TEXTURED_MATTE_NONREFLECTIVE_FULL_CUTOFF = 2223,
            SHADELESS_TEXTURED_MATTE_NONREFLECTIVE_FULL_OPAQUE = 1071,
            SHADELESS_TEXTURED_MATTE_NONREFLECTIVE_FULL_TRANSPARENT = 1647,
            SHADELESS_TEXTURED_MATTE_NONREFLECTIVE_SHADOWLESS_CUTOFF = 1935,
            SHADELESS_TEXTURED_MATTE_NONREFLECTIVE_SHADOWLESS_OPAQUE = 783,
            SHADELESS_TEXTURED_MATTE_NONREFLECTIVE_SHADOWLESS_TRANSPARENT = 1359,
            SHADELESS_TEXTURED_MATTE_REALTIME_CASTER_CUTOFF = 2151,
            SHADELESS_TEXTURED_MATTE_REALTIME_CASTER_OPAQUE = 999,
            SHADELESS_TEXTURED_MATTE_REALTIME_CASTER_TRANSPARENT = 1575,
            SHADELESS_TEXTURED_MATTE_REALTIME_FULL_CUTOFF = 2295,
            SHADELESS_TEXTURED_MATTE_REALTIME_FULL_OPAQUE = 1143,
            SHADELESS_TEXTURED_MATTE_REALTIME_FULL_TRANSPARENT = 1719,
            SHADELESS_TEXTURED_MATTE_REALTIME_SHADOWLESS_CUTOFF = 2007,
            SHADELESS_TEXTURED_MATTE_REALTIME_SHADOWLESS_OPAQUE = 855,
            SHADELESS_TEXTURED_MATTE_REALTIME_SHADOWLESS_TRANSPARENT = 1431,
            SHADELESS_TEXTURED_SPECULATED_BAKED_CASTER_CUTOFF = 2127,
            SHADELESS_TEXTURED_SPECULATED_BAKED_CASTER_OPAQUE = 975,
            SHADELESS_TEXTURED_SPECULATED_BAKED_CASTER_TRANSPARENT = 1551,
            SHADELESS_TEXTURED_SPECULATED_BAKED_FULL_CUTOFF = 2271,
            SHADELESS_TEXTURED_SPECULATED_BAKED_FULL_OPAQUE = 1119,
            SHADELESS_TEXTURED_SPECULATED_BAKED_FULL_TRANSPARENT = 1695,
            SHADELESS_TEXTURED_SPECULATED_BAKED_SHADOWLESS_CUTOFF = 1983,
            SHADELESS_TEXTURED_SPECULATED_BAKED_SHADOWLESS_OPAQUE = 831,
            SHADELESS_TEXTURED_SPECULATED_BAKED_SHADOWLESS_TRANSPARENT = 1407,
            SHADELESS_TEXTURED_SPECULATED_NONREFLECTIVE_CASTER_CUTOFF = 2091,
            SHADELESS_TEXTURED_SPECULATED_NONREFLECTIVE_CASTER_OPAQUE = 939,
            SHADELESS_TEXTURED_SPECULATED_NONREFLECTIVE_CASTER_TRANSPARENT = 1515,
            SHADELESS_TEXTURED_SPECULATED_NONREFLECTIVE_FULL_CUTOFF = 2235,
            SHADELESS_TEXTURED_SPECULATED_NONREFLECTIVE_FULL_OPAQUE = 1083,
            SHADELESS_TEXTURED_SPECULATED_NONREFLECTIVE_FULL_TRANSPARENT = 1659,
            SHADELESS_TEXTURED_SPECULATED_NONREFLECTIVE_SHADOWLESS_CUTOFF = 1947,
            SHADELESS_TEXTURED_SPECULATED_NONREFLECTIVE_SHADOWLESS_OPAQUE = 795,
            SHADELESS_TEXTURED_SPECULATED_NONREFLECTIVE_SHADOWLESS_TRANSPARENT = 1371,
            SHADELESS_TEXTURED_SPECULATED_REALTIME_CASTER_CUTOFF = 2163,
            SHADELESS_TEXTURED_SPECULATED_REALTIME_CASTER_OPAQUE = 1011,
            SHADELESS_TEXTURED_SPECULATED_REALTIME_CASTER_TRANSPARENT = 1587,
            SHADELESS_TEXTURED_SPECULATED_REALTIME_FULL_CUTOFF = 2307,
            SHADELESS_TEXTURED_SPECULATED_REALTIME_FULL_OPAQUE = 1155,
            SHADELESS_TEXTURED_SPECULATED_REALTIME_FULL_TRANSPARENT = 1731,
            SHADELESS_TEXTURED_SPECULATED_REALTIME_SHADOWLESS_CUTOFF = 2019,
            SHADELESS_TEXTURED_SPECULATED_REALTIME_SHADOWLESS_OPAQUE = 867,
            SHADELESS_TEXTURED_SPECULATED_REALTIME_SHADOWLESS_TRANSPARENT = 1443,
            WHITE_POS = 1,
            WHITE_POS_NRM = 2,
            WHITE_POS_NRM_UV = 4,
            WHITE_POS_UV = 3,
        };
        namespace stage {

            enum Id : core::Id {
                FRAGMENT = 0,
                VERTEX = 1,
            };
        }

        typedef enum {
            VEC3F32,
            VEC2F32,
        } VertexAttribute;

        typedef struct
        {
            typedef enum : unsigned int {
                UNIFORM,
                SAMPER2D,
                // Add whenever needed
            } Type;
            std::vector<stage::Id> binding_stages;
            unsigned int count;
            Type t;
        } ResourceDescription;

        class Shader : public core::asset::Asset {
        private:
            static const std::vector<ResourceDescription> buffer_rsc_des;
            static const std::vector<ResourceDescription> textured_rsc_des;
            static const std::vector<VertexAttribute> has_pos;
            static const std::vector<VertexAttribute> has_pos_nrm;
            static const std::vector<VertexAttribute> has_pos_uv;
            static const std::vector<VertexAttribute> has_pos_nrm_uv;

        protected:
            static const std::vector<stage::Id> graphic_2_stage;
            Shader();

        public:
            virtual ~Shader();
            virtual const std::vector<stage::Id>& get_stages_ids() const = 0;
            virtual void use() = 0;
            static std::shared_ptr<Shader> read(core::Id sid, system::File* file, Engine* engine, std::shared_ptr<core::EndCaller> end);
            static const std::vector<ResourceDescription>& get_resources_descriptions(Id id);
            static const std::vector<VertexAttribute>& get_vertex_atributes(Id id);
            static unsigned int get_uniform_size(core::Id id);
            static unsigned int get_vertex_real_count(core::Id id);
        };
    }
}
}
#endif
