set(VCPKG_TARGET_ARCHITECTURE x64)
set(VCPKG_CRT_LINKAGE dynamic)
set(VCPKG_LIBRARY_LINKAGE dynamic)

set(VCPKG_C_FLAGS "/MP /arch:AVX2 /Oi")
set(VCPKG_CXX_FLAGS "/MP /arch:AVX2 /Oi")
set(VCPKG_C_FLAGS_RELEASE "/O2 /GL /Gw")
set(VCPKG_CXX_FLAGS_RELEASE "/O2 /GL /Gw")
set(VCPKG_LINKER_FLAGS_RELEASE "/LTCG /OPT:REF,ICF")