FROM ubuntu:20.04
RUN apt update
RUN apt dist-upgrade -y
RUN apt install -y sudo
RUN apt install -y gcc-10
RUN apt install -y g++-10
RUN apt install -y make
RUN apt install -y cmake
RUN apt install -y python3 
RUN apt install -y git
RUN apt install -y ssh
RUN apt install -y tar
RUN apt install -y gzip
RUN apt install -y ca-certificates
RUN apt install -y curl
RUN apt install -y lcov
RUN apt install -y gcovr
RUN apt install -y wget
RUN apt install -y libsndio-dev
RUN apt install -y doxygen