#include "gx-plt-and-key.hpp"
#ifdef GX_PLATFORM_INTERFACE_ANDROID
#include "../gx-plt-log.hpp"
#include <android/keycodes.h>
#include <boost/container/flat_map.hpp>

static const boost::container::flat_map<std::int32_t, gearoenix::platform::key::Id> gearoenix_key_map {
    { AKEYCODE_DPAD_LEFT, gearoenix::platform::key::Id::Left },
    { AKEYCODE_META_LEFT, gearoenix::platform::key::Id::Left },
    { AKEYCODE_SOFT_LEFT, gearoenix::platform::key::Id::Left },
    { AKEYCODE_SYSTEM_NAVIGATION_LEFT, gearoenix::platform::key::Id::Left },
    { AKEYCODE_DPAD_RIGHT, gearoenix::platform::key::Id::Right },
    { AKEYCODE_META_RIGHT, gearoenix::platform::key::Id::Right },
    { AKEYCODE_SOFT_RIGHT, gearoenix::platform::key::Id::Right },
    { AKEYCODE_SYSTEM_NAVIGATION_RIGHT, gearoenix::platform::key::Id::Right },
    { AKEYCODE_DPAD_UP, gearoenix::platform::key::Id::Up },
    { AKEYCODE_SYSTEM_NAVIGATION_UP, gearoenix::platform::key::Id::Up },
    { AKEYCODE_DPAD_DOWN, gearoenix::platform::key::Id::Down },
    { AKEYCODE_SYSTEM_NAVIGATION_DOWN, gearoenix::platform::key::Id::Down },
    { AKEYCODE_ESCAPE, gearoenix::platform::key::Id::Escape },
    { AKEYCODE_A, gearoenix::platform::key::Id::A },
    { AKEYCODE_B, gearoenix::platform::key::Id::B },
    { AKEYCODE_C, gearoenix::platform::key::Id::C },
    { AKEYCODE_D, gearoenix::platform::key::Id::D },
    { AKEYCODE_E, gearoenix::platform::key::Id::E },
    { AKEYCODE_F, gearoenix::platform::key::Id::F },
    { AKEYCODE_G, gearoenix::platform::key::Id::G },
    { AKEYCODE_H, gearoenix::platform::key::Id::H },
    { AKEYCODE_I, gearoenix::platform::key::Id::I },
    { AKEYCODE_J, gearoenix::platform::key::Id::J },
    { AKEYCODE_K, gearoenix::platform::key::Id::K },
    { AKEYCODE_L, gearoenix::platform::key::Id::L },
    { AKEYCODE_M, gearoenix::platform::key::Id::M },
    { AKEYCODE_N, gearoenix::platform::key::Id::N },
    { AKEYCODE_O, gearoenix::platform::key::Id::O },
    { AKEYCODE_P, gearoenix::platform::key::Id::P },
    { AKEYCODE_Q, gearoenix::platform::key::Id::Q },
    { AKEYCODE_R, gearoenix::platform::key::Id::R },
    { AKEYCODE_S, gearoenix::platform::key::Id::S },
    { AKEYCODE_T, gearoenix::platform::key::Id::T },
    { AKEYCODE_U, gearoenix::platform::key::Id::U },
    { AKEYCODE_V, gearoenix::platform::key::Id::V },
    { AKEYCODE_W, gearoenix::platform::key::Id::W },
    { AKEYCODE_X, gearoenix::platform::key::Id::X },
    { AKEYCODE_Y, gearoenix::platform::key::Id::Y },
    { AKEYCODE_Z, gearoenix::platform::key::Id::Z },
    { AKEYCODE_0, gearoenix::platform::key::Id::Num0 },
    { AKEYCODE_1, gearoenix::platform::key::Id::Num1 },
    { AKEYCODE_2, gearoenix::platform::key::Id::Num2 },
    { AKEYCODE_3, gearoenix::platform::key::Id::Num3 },
    { AKEYCODE_4, gearoenix::platform::key::Id::Num4 },
    { AKEYCODE_5, gearoenix::platform::key::Id::Num5 },
    { AKEYCODE_6, gearoenix::platform::key::Id::Num6 },
    { AKEYCODE_7, gearoenix::platform::key::Id::Num7 },
    { AKEYCODE_8, gearoenix::platform::key::Id::Num8 },
    { AKEYCODE_9, gearoenix::platform::key::Id::Num9 },
    { AKEYCODE_NUMPAD_0, gearoenix::platform::key::Id::Numpad0 },
    { AKEYCODE_NUMPAD_1, gearoenix::platform::key::Id::Numpad1 },
    { AKEYCODE_NUMPAD_2, gearoenix::platform::key::Id::Numpad2 },
    { AKEYCODE_NUMPAD_3, gearoenix::platform::key::Id::Numpad3 },
    { AKEYCODE_NUMPAD_4, gearoenix::platform::key::Id::Numpad4 },
    { AKEYCODE_NUMPAD_5, gearoenix::platform::key::Id::Numpad5 },
    { AKEYCODE_NUMPAD_6, gearoenix::platform::key::Id::Numpad6 },
    { AKEYCODE_NUMPAD_7, gearoenix::platform::key::Id::Numpad7 },
    { AKEYCODE_NUMPAD_8, gearoenix::platform::key::Id::Numpad8 },
    { AKEYCODE_NUMPAD_9, gearoenix::platform::key::Id::Numpad9 },
    { AKEYCODE_SPACE, gearoenix::platform::key::Id::Space },
    { AKEYCODE_LEFT_BRACKET, gearoenix::platform::key::Id::LeftBracket },
    { AKEYCODE_RIGHT_BRACKET, gearoenix::platform::key::Id::RightBracket },
    { AKEYCODE_GRAVE, gearoenix::platform::key::Id::Tilda },
    { AKEYCODE_DEL, gearoenix::platform::key::Id::Backspace },
    { AKEYCODE_BACKSLASH, gearoenix::platform::key::Id::Backslash },
    { AKEYCODE_SLASH, gearoenix::platform::key::Id::Slash },
    { AKEYCODE_APOSTROPHE, gearoenix::platform::key::Id::Quote },
    { AKEYCODE_SEMICOLON, gearoenix::platform::key::Id::Semicolon },
    { AKEYCODE_MINUS, gearoenix::platform::key::Id::Minus },
    { AKEYCODE_EQUALS, gearoenix::platform::key::Id::Equal },
    { AKEYCODE_TAB, gearoenix::platform::key::Id::Tab },
    { AKEYCODE_CAPS_LOCK, gearoenix::platform::key::Id::CapsLock },
    { AKEYCODE_SHIFT_LEFT, gearoenix::platform::key::Id::LeftShift },
    { AKEYCODE_SHIFT_RIGHT, gearoenix::platform::key::Id::RightShift },
    { AKEYCODE_CTRL_LEFT, gearoenix::platform::key::Id::LeftControl },
    { AKEYCODE_CTRL_RIGHT, gearoenix::platform::key::Id::RightControl },
    { AKEYCODE_ALT_LEFT, gearoenix::platform::key::Id::LeftAlt },
    { AKEYCODE_ALT_RIGHT, gearoenix::platform::key::Id::RightAlt },
    { AKEYCODE_MENU, gearoenix::platform::key::Id::Menu },
    { AKEYCODE_COMMA, gearoenix::platform::key::Id::Comma },
    { AKEYCODE_PERIOD, gearoenix::platform::key::Id::Dot },
    { AKEYCODE_F1, gearoenix::platform::key::Id::F1 },
    { AKEYCODE_F2, gearoenix::platform::key::Id::F2 },
    { AKEYCODE_F3, gearoenix::platform::key::Id::F3 },
    { AKEYCODE_F4, gearoenix::platform::key::Id::F4 },
    { AKEYCODE_F5, gearoenix::platform::key::Id::F5 },
    { AKEYCODE_F6, gearoenix::platform::key::Id::F6 },
    { AKEYCODE_F7, gearoenix::platform::key::Id::F7 },
    { AKEYCODE_F8, gearoenix::platform::key::Id::F8 },
    { AKEYCODE_F9, gearoenix::platform::key::Id::F9 },
    { AKEYCODE_F10, gearoenix::platform::key::Id::F10 },
    { AKEYCODE_F11, gearoenix::platform::key::Id::F11 },
    { AKEYCODE_F12, gearoenix::platform::key::Id::F12 },
    { AKEYCODE_INSERT, gearoenix::platform::key::Id::Insert },
    { AKEYCODE_FORWARD_DEL, gearoenix::platform::key::Id::Delete },
    { AKEYCODE_HOME, gearoenix::platform::key::Id::Home },
    { AKEYCODE_MOVE_END, gearoenix::platform::key::Id::End },
    { AKEYCODE_PAGE_DOWN, gearoenix::platform::key::Id::PageDown },
    { AKEYCODE_PAGE_UP, gearoenix::platform::key::Id::PageUp },
    { AKEYCODE_SCROLL_LOCK, gearoenix::platform::key::Id::ScrollLock },
    { AKEYCODE_MEDIA_PAUSE, gearoenix::platform::key::Id::Pause },
    { AKEYCODE_NUM_LOCK, gearoenix::platform::key::Id::NumpadLock },
    { AKEYCODE_NUMPAD_DIVIDE, gearoenix::platform::key::Id::NumpadSlash },
    { AKEYCODE_NUMPAD_MULTIPLY, gearoenix::platform::key::Id::NumpadStar },
    { AKEYCODE_NUMPAD_SUBTRACT, gearoenix::platform::key::Id::NumpadMinus },
    { AKEYCODE_NUMPAD_ADD, gearoenix::platform::key::Id::NumpadPlus },
    { AKEYCODE_NUMPAD_ENTER, gearoenix::platform::key::Id::NumpadEnter },
    { AKEYCODE_NUMPAD_DOT, gearoenix::platform::key::Id::NumpadDot },
};

gearoenix::platform::key::Id gearoenix::platform::convert_android_key(const std::int32_t key_code) noexcept
{
    if (const auto search = gearoenix_key_map.find(key_code); gearoenix_key_map.end() != search)
        return search->second;
    GX_LOG_E("Unhandled key: " << static_cast<int>(key_code));
    return gearoenix::platform::key::Id::Unknown;
}

#endif