#ifndef GEAROENIX_VULKAN_SHADER_BINDINGS_HPP
#define GEAROENIX_VULKAN_SHADER_BINDINGS_HPP

#define GX_VK_BIND_RAY_VERTICES 0
#define GX_VK_BIND_RAY_INDICES 1
#define GX_VK_BIND_RAY_MATERIALS 2
#define GX_VK_BIND_RAY_2D_TEXTURES 3
#define GX_VK_BIND_RAY_CUBE_TEXTURES 4
#define GX_VK_BIND_RAY_MESH 5
#define GX_VK_BIND_RAY_TLAS 6
#define GX_VK_BIND_RAY_OUT_IMAGE 7
#define GX_VK_BIND_RAY_CAMERA 8
#define GX_VK_BIND_RAY_MAX 9

#endif