#ifndef GEAROENIX_RENDER_GLTF_INCLUDE_HPP
#define GEAROENIX_RENDER_GLTF_INCLUDE_HPP

#define STB_IMAGE_IMPLEMENTATION
#define STB_IMAGE_WRITE_IMPLEMENTATION
#define TINYGLTF_NOEXCEPTION
#define TINYGLTF_IMPLEMENTATION
#include <tiny_gltf.h>

#include "gx-rnd-gltf-loader.hpp"

#endif