#pragma once
#include "../core/macro/gx-cr-mcr-stringifier.hpp"

#define GX_RENDER_MAX_DIRECTIONAL_LIGHTS 8
#define GX_RENDER_MAX_DIRECTIONAL_LIGHTS_STR GX_STRINGIFY(GX_RENDER_MAX_DIRECTIONAL_LIGHTS)
#define GX_RENDER_MAX_DIRECTIONAL_LIGHTS_SHADOW_CASTER 8
#define GX_RENDER_MAX_DIRECTIONAL_LIGHTS_SHADOW_CASTER_STR GX_STRINGIFY(GX_RENDER_MAX_DIRECTIONAL_LIGHTS_SHADOW_CASTER)
#define GX_RENDER_MAX_POINT_LIGHTS 8
#define GX_RENDER_MAX_POINT_LIGHTS_STR GX_STRINGIFY(GX_RENDER_MAX_POINT_LIGHTS)
#define GX_RENDER_MAX_CONE_LIGHTS 8
#define GX_RENDER_MAX_CONE_LIGHTS_STR GX_STRINGIFY(GX_RENDER_MAX_CONE_LIGHTS)
#define GX_RENDER_MAX_SHADOW_CASCADES 4
#define GX_RENDER_MAX_SHADOW_CASCADES_STR GX_STRINGIFY(GX_RENDER_MAX_SHADOW_CASCADES)
#define GX_RENDER_MAX_DIRECTIONAL_LIGHTS_CASCADES (GX_RENDER_MAX_SHADOW_CASCADES * GX_RENDER_MAX_DIRECTIONAL_LIGHTS_SHADOW_CASTER)
#define GX_RENDER_MAX_DIRECTIONAL_LIGHTS_CASCADES_STR GX_STRINGIFY(GX_RENDER_MAX_DIRECTIONAL_LIGHTS_CASCADES)
#define GX_RENDER_MAX_RUNTIME_REFLECTION_MIPMAPS_COUNT 10
#define GX_RENDER_DEFAULT_RUNTIME_REFLECTION_ENVIRONMENT_RESOLUTION 512
#define GX_RENDER_DEFAULT_RUNTIME_REFLECTION_IRRADIANCE_RESOLUTION 32
#define GX_RENDER_DEFAULT_RUNTIME_REFLECTION_RADIANCE_RESOLUTION 128
#define GX_RENDER_DEFAULT_BRDFLUT_RESOLUTION 256
#define GX_RENDER_MAX_BONES_COUNT 128
#define GX_RENDER_MAX_BLOOM_DOWN_SAMPLE_COUNT 6
#define GX_RENDER_DEFAULT_CAMERA_TARGET_MIPS_COUNT (GX_RENDER_MAX_BLOOM_DOWN_SAMPLE_COUNT + 1)

#include "../platform/gx-plt-build-configuration.hpp"

#if GX_PLATFORM_WINDOWS
// #define GX_RENDER_VULKAN_ENABLED
#if !GX_PLATFORM_INTERFACE_SDL2
#define GX_RENDER_DIRECT3D_ENABLED true
#else
#define GX_RENDER_OPENGL_ENABLED true
#endif
#elif GX_PLATFORM_LINUX
#define GX_RENDER_OPENGL_ENABLED true
// #define GX_RENDER_VULKAN_ENABLED true
#elif GX_PLATFORM_APPLE
//#define GX_RENDER_METAL_ENABLED true
#define GX_RENDER_OPENGL_ENABLED true
#elif GX_PLATFORM_ANDROID
#define GX_RENDER_OPENGL_ENABLED true
// #define GX_RENDER_VULKAN_ENABLED true
#elif GX_PLATFORM_WEBASSEMBLY
#define GX_RENDER_OPENGL_ENABLED true
#else
#error "Unexpected/unimplemented platform."
#endif