FUNCTION(GX_FIND_BUILDER)
    IF(APPLE)
        MESSAGE(FATAL_ERROR "Unsupported platform")
    ELSEIF(LINUX)
        SET(GX_GMAKE_EXE "gmake")
    ELSEIF(MSVC)
        SET(GX_MSBUILD_EXE "C:/Program Files (x86)/Microsoft Visual Studio/2019/Professional/MSBuild/Current/Bin/amd64/MSBuild.exe")
        IF(NOT EXISTS ${GX_MSBUILD_EXE})
            SET(GX_MSBUILD_EXE "C:/Program Files (x86)/Microsoft Visual Studio/2019/Community/MSBuild/Current/Bin/amd64/MSBuild.exe")
        ENDIF()
        IF(NOT EXISTS ${GX_MSBUILD_EXE})
            MESSAGE(FATAL_ERROR "Can not find the MSBuild")
        ENDIF()
        SET(GX_MSBUILD_EXE ${GX_MSBUILD_EXE} PARENT_SCOPE)
    ELSE()
        MESSAGE(FATAL_ERROR "Unsupported platform")
    ENDIF()
ENDFUNCTION()