FUNCTION(GX_COMPILE_SHADER SHADER ALL_INCLUDES SHADER_OUT)
	IF (WIN32)
		GET_FILENAME_COMPONENT(PARENT_DIR ${CMAKE_SOURCE_DIR} DIRECTORY)
		GET_FILENAME_COMPONENT(FILE_NAME ${SHADER} NAME)
		GET_FILENAME_COMPONENT(FILE_NAME_WO_EXT ${SHADER} NAME_WLE)

		SET(SHADER_TYPE ${CMAKE_MATCH_1})
		FIND_PROGRAM(DXC dxc PATHS ${GX_DXC_BINARY_DIR} REQUIRED NO_DEFAULT_PATH)

		SET(OUTPUT_PATH ${CMAKE_BINARY_DIR}/${FILE_NAME_WO_EXT}.cso)

		ADD_CUSTOM_COMMAND(
			   OUTPUT ${OUTPUT_PATH}
			   COMMAND ${DXC} -Qembed_debug -Qstrip_reflect -nologo -Zi -Od -T ${SHADER_TYPE}_6_5 -E main -Fo ${OUTPUT_PATH} ${SHADER}
			   DEPENDS ${ALL_INCLUDES}
			   COMMENT "Compiling shader ${FILE_NAME}..."
			   VERBATIM)

		SET_SOURCE_FILES_PROPERTIES(${OUTPUT_PATH} PROPERTIES GENERATED TRUE)
		SET(${SHADER_OUT} ${OUTPUT_PATH} PARENT_SCOPE)
	ENDIF ()
ENDFUNCTION(GX_COMPILE_SHADER)