function(gx_replace_flag FLAGS EXISTING_FLAG NEW_FLAG)
    message(STATUS "Searching in flags: ${FLAGS} for ${EXISTING_FLAG} and replacing it with ${NEW_FLAG} ...")
    string(FIND ${${FLAGS}} ${NEW_FLAG} INDEX)
    if(NOT INDEX EQUAL -1)
        message(STATUS "Flag: ${NEW_FLAG} already exists in ${FLAGS}.")
        return()
    endif()
    string(FIND ${${FLAGS}} ${EXISTING_FLAG} INDEX)
    if(INDEX EQUAL -1)
        message(STATUS "Flag: ${EXISTING_FLAG} didn't exist in ${FLAGS}.")
        set(${FLAGS} "${${FLAGS}} ${NEW_FLAG}" PARENT_SCOPE)
    else()
        message(STATUS "Flag: ${EXISTING_FLAG} existed in ${FLAGS}.")
        string(REPLACE ${EXISTING_FLAG} ${NEW_FLAG} ${FLAGS} ${${FLAGS}} PARENT_SCOPE)
    endif()
endfunction(gx_replace_flag)